from .add_quote import dp
from .add_quote_for_user import dp
from .inline_query import dp
from .show_quote_by_type import dp
from .profile import dp
from .admin_menu import dp
from .check_quote import dp
from .random_quote import dp
from .help import dp
from .edit_anime_quote import dp
from .detect_anime_by_image import dp